import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/ui/navbar";
import { Footer } from "@/components/ui/footer";
import { cn } from "@/lib/utils";

const inter = Lato({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-background-50")}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
